server:
  port: 9091
spring:
  application:
    name: service-consumer

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
feign:
  name: service-provider

management:
  endpoints:
    web:
      exposure:
        include: '*'

